name: Run Tests Workflow to development

on:
  push: 
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v5
      - user: actions/setup-node@v5
        with:
          node-version: 'lst/*'
      - name: Install dependencies
        run: npm install
      - name: Set up environment variables using secrets
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" >> .env
          echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> .env
          echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> .env
      - name: Run tests
        run: npm test
